/** yt-dlp site keys CherryBox matches against download URLs (substring match). */
window.DownloadSupportedSites = [
  { id: 'pornhub', label: 'PornHub', testUrl: 'https://www.pornhub.com/' },
  { id: 'xvideos', label: 'XVideos', testUrl: 'https://www.xvideos.com/' },
  { id: 'xhamster', label: 'xHamster', testUrl: 'https://xhamster.com/' },
  { id: 'youporn', label: 'YouPorn', testUrl: 'https://www.youporn.com/' },
  { id: 'redtube', label: 'RedTube', testUrl: 'https://www.redtube.com/' },
  { id: 'tube8', label: 'Tube8', testUrl: 'https://www.tube8.com/' },
  { id: 'spankbang', label: 'SpankBang', testUrl: 'https://spankbang.com/' },
  { id: 'eporner', label: 'Eporner', testUrl: 'https://www.eporner.com/' },
  { id: 'xnxx', label: 'XNXX', testUrl: 'https://www.xnxx.com/' },
  { id: 'onlyfans', label: 'OnlyFans', testUrl: 'https://onlyfans.com/' },
  { id: 'fansly', label: 'Fansly', testUrl: 'https://fansly.com/' },
  { id: 'youtube', label: 'YouTube', testUrl: 'https://www.youtube.com/feed/subscriptions' },
  { id: 'vimeo', label: 'Vimeo', testUrl: 'https://vimeo.com/' },
  { id: 'twitch', label: 'Twitch', testUrl: 'https://www.twitch.tv/' },
  { id: 'twitter', label: 'Twitter / X', testUrl: 'https://x.com/' },
  { id: 'instagram', label: 'Instagram', testUrl: 'https://www.instagram.com/' },
  { id: 'reddit', label: 'Reddit', testUrl: 'https://www.reddit.com/' },
  { id: 'tiktok', label: 'TikTok', testUrl: 'https://www.tiktok.com/' },
  { id: 'facebook', label: 'Facebook', testUrl: 'https://www.facebook.com/' },
  { id: 'dailymotion', label: 'Dailymotion', testUrl: 'https://www.dailymotion.com/' },
  { id: 'bilibili', label: 'Bilibili', testUrl: 'https://www.bilibili.com/' },
  { id: 'niconico', label: 'Niconico', testUrl: 'https://www.nicovideo.jp/' },
  { id: 'rumble', label: 'Rumble', testUrl: 'https://rumble.com/' },
  { id: 'soundcloud', label: 'SoundCloud', testUrl: 'https://soundcloud.com/' },
  { id: 'bandcamp', label: 'Bandcamp', testUrl: 'https://bandcamp.com/' },
  { id: 'mixcloud', label: 'Mixcloud', testUrl: 'https://www.mixcloud.com/' },
  { id: 'archiveorg', label: 'Internet Archive', testUrl: 'https://archive.org/' },
  { id: 'vidme', label: 'Vidme (legacy)', testUrl: '' },
  { id: 'porntrex', label: 'PornTrex', testUrl: 'https://www.porntrex.com/' },
  { id: 'hentaihaven', label: 'Hentai Haven', testUrl: '' },
  { id: 'rule34video', label: 'Rule34Video', testUrl: '' },
  { id: 'manyvids', label: 'ManyVids', testUrl: 'https://www.manyvids.com/' },
  { id: 'chaturbate', label: 'Chaturbate', testUrl: 'https://chaturbate.com/' },
  { id: 'myfreecams', label: 'MyFreeCams', testUrl: 'https://www.myfreecams.com/' },
  { id: 'streamable', label: 'Streamable', testUrl: 'https://streamable.com/' },
  { id: 'gfycat', label: 'Gfycat', testUrl: '' },
  { id: 'imgur', label: 'Imgur', testUrl: 'https://imgur.com/' },
  { id: 'kick', label: 'Kick', testUrl: 'https://kick.com/' },
  { id: 'odysee', label: 'Odysee', testUrl: 'https://odysee.com/' },
  { id: 'peertube', label: 'PeerTube', testUrl: '' },
];
